version: '3.5' 

services: 
    proxy: 
      image: nginx
      volumes: 
        - ./conf/nginx.conf:/etc/nginx/nginx.conf
        - /var/run/docker.sock:/tmp/docker.sock:ro
      ports: 
        - 80:80 

    postgres:
       image: postgres
       environment:
         - POSTGRES_PASSWORD=verysecret
    redis:
       image: redis
       ports: 
         - 6379:6379
    backend:
       image: backend
       ports: 
           - 8000:8000
       environment:
         - REDIS=redis
         - REDIS_PORT=6379
         - DB_PASSWORD=verysecret
         - DB_USERNAME=postgres
         - DB_HOST=postgres
       restart: unless-stopped
 
    front:
       image: front
       ports: 
        - 5000:5000
       environment:
           - API_URL=/api

