version: '3'

services:
    ml-front:
       image: ml-front
       ports: 
           - 3000:3000
            
    ml-back:
       image: ml-back
       ports:
          - 5000:5000
       volumes:
          - model:/src/model
          - images:/src/images
    
    learning:
       image: training
       volumes:
          - model:/src/model
          - images:/src/imgs

volumes:
  model:
  images:

    
