version: '3'

services:
     first-vol-exercise:
           image: devopsdockeruh/first_volume_exercise
           build: .
           volumes:
             - ./logs/logs.txt:/usr/app/logs.txt
           container_name: first-vol


