version: '3'

services:
    postgres:
       image: postgres
       environment:
         - POSTGRES_PASSWORD=verysecret
    redis:
       image: redis
       ports:
          - 6379:6379
    backend:
       image: backend
       ports: 
         - 8000:8000
       environment:
         - FRONT_URL=http://localhost:5000
         - REDIS=redis
         - REDIS_PORT=6379
         - DB_PASSWORD=verysecret
         - DB_USERNAME=postgres
         - DB_HOST=postgres
 
    front:
       image: front
       ports: 
           - 5000:5000
       environment:
           - API_URL=http://localhost:8000


